# Generated by Django 5.1.6 on 2025-03-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('Room_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Room_Type', models.CharField(choices=[('Standart', 'Standart'), ('Lyuks', 'Lyuks'), ('Premium', 'Premium')], max_length=20)),
                ('Room_Floor', models.IntegerField()),
                ('Room_Number', models.IntegerField()),
                ('Capacity', models.IntegerField(default=1)),
                ('View', models.CharField(blank=True, max_length=100, null=True)),
                ('Is_Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoomRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Date', models.DateField()),
                ('Daily_Room_Rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('Room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
            options={
                'unique_together': {('Day_Date', 'Room_ID')},
            },
        ),
    ]
