# Generated by Django 5.1.6 on 2025-04-04 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mehmonxona nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('city', models.CharField(max_length=200, verbose_name='Shahar')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Reyting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Mehmonxona',
                'verbose_name_plural': 'Mehmonxonalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='Xona raqami')),
                ('room_type', models.CharField(choices=[('ST', 'Standart'), ('CF', 'Komfort'), ('LX', 'Lyuks'), ('SU', 'Syuyt'), ('AP', 'Apartament')], default='ST', max_length=2, verbose_name='Xona turi')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bir kecha narxi')),
                ('capacity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Sig'imi (kishi)")),
                ('beds', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Karavotlar soni')),
                ('has_breakfast', models.BooleanField(default=False, verbose_name='Nonushta kiritilgan')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.hotel', verbose_name='Mehmonxona')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['hotel', 'room_number'],
                'unique_together': {('hotel', 'room_number')},
            },
        ),
    ]
