# Generated by Django 5.1.6 on 2025-04-04 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_room_options_alter_room_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Sig'imi"),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qavat'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=False, verbose_name='Konditsioner'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_bathroom',
            field=models.BooleanField(default=False, verbose_name='Hammom'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_breakfast',
            field=models.BooleanField(default=False, verbose_name='Nonushta'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_minibar',
            field=models.BooleanField(default=False, verbose_name='Minibar'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_safe',
            field=models.BooleanField(default=False, verbose_name='Seif'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=False, verbose_name='Televizor'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
    ]
