# Generated by Django 4.0.8 on 2025-05-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_room_capacity_room_description_room_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Mehmon ismi')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('check_in_date', models.DateField(verbose_name='Kirish sanasi')),
                ('check_out_date', models.DateField(verbose_name='Chiqish sanasi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Bandlov',
                'verbose_name_plural': 'Bandlovlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
