# Generated by Django 4.0.8 on 2025-05-04 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='Invoice Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice PDF')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
